spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/rep?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: root
logging:
  level:
    com.rep.mapper: DEBUG
